import type { Exercise } from '../types'
import { db } from './schema'

const SEED_IDS = new Set<string>()

/** Stable IDs for overlapping legacy seeds so existing programs keep working. */
export const SEED_EXERCISES: Exercise[] = [
  // —— Legacy IDs (names aligned with catalog) ——
  {
    id: 'seed-bench',
    name: 'Barbell bench press',
    kind: 'resistance',
    tags: ['upper-push', 'chest', 'push'],
    isCustom: false,
  },
  {
    id: 'seed-squat',
    name: 'Back squat',
    kind: 'resistance',
    tags: ['lower-compound', 'legs'],
    isCustom: false,
  },
  {
    id: 'seed-deadlift',
    name: 'Conventional deadlift',
    kind: 'resistance',
    tags: ['lower-compound', 'pull', 'legs'],
    isCustom: false,
  },
  {
    id: 'seed-row',
    name: 'Barbell rows',
    kind: 'resistance',
    tags: ['upper-pull', 'pull', 'back'],
    isCustom: false,
  },
  {
    id: 'seed-ohp',
    name: 'Overhead press',
    kind: 'resistance',
    tags: ['upper-push', 'push', 'shoulders'],
    isCustom: false,
  },
  {
    id: 'seed-pullup',
    name: 'Pull-ups',
    kind: 'resistance',
    tags: ['upper-pull', 'pull', 'back'],
    isCustom: false,
  },

  // 🔴 Plyometrics
  {
    id: 'seed-plyo-pogos-dl',
    name: 'Pogos (double-leg)',
    kind: 'resistance',
    tags: ['plyometrics', 'power'],
    isCustom: false,
  },
  {
    id: 'seed-plyo-pogos-sl',
    name: 'Single-leg pogos',
    kind: 'resistance',
    tags: ['plyometrics', 'power', 'unilateral'],
    isCustom: false,
  },
  {
    id: 'seed-plyo-broad-jump',
    name: 'Broad jumps',
    kind: 'resistance',
    tags: ['plyometrics', 'power'],
    isCustom: false,
  },
  {
    id: 'seed-plyo-bounding',
    name: 'Bounding (alternating)',
    kind: 'resistance',
    tags: ['plyometrics', 'power'],
    isCustom: false,
  },
  {
    id: 'seed-plyo-lateral-bounds',
    name: 'Lateral bounds (skaters)',
    kind: 'resistance',
    tags: ['plyometrics', 'power'],
    isCustom: false,
  },
  {
    id: 'seed-plyo-sl-lat-hop',
    name: 'Single-leg lateral hops (stick)',
    kind: 'resistance',
    tags: ['plyometrics', 'power', 'unilateral'],
    isCustom: false,
  },
  {
    id: 'seed-plyo-box-jump',
    name: 'Box jumps',
    kind: 'resistance',
    tags: ['plyometrics', 'power'],
    isCustom: false,
  },
  {
    id: 'seed-plyo-depth-drop',
    name: 'Depth drops (stick landing)',
    kind: 'resistance',
    tags: ['plyometrics', 'power'],
    isCustom: false,
  },
  {
    id: 'seed-plyo-drop-jump',
    name: 'Drop jumps (reactive)',
    kind: 'resistance',
    tags: ['plyometrics', 'power'],
    isCustom: false,
  },
  {
    id: 'seed-plyo-split-squat-jump',
    name: 'Split squat jumps',
    kind: 'resistance',
    tags: ['plyometrics', 'power'],
    isCustom: false,
  },

  // 🟠 Lower body compound (additional)
  {
    id: 'seed-lc-front-squat',
    name: 'Front squat',
    kind: 'resistance',
    tags: ['lower-compound', 'legs'],
    isCustom: false,
  },
  {
    id: 'seed-lc-trap-bar-deadlift',
    name: 'Trap bar deadlift',
    kind: 'resistance',
    tags: ['lower-compound', 'legs'],
    isCustom: false,
  },
  {
    id: 'seed-lc-sumo-deadlift',
    name: 'Sumo deadlift',
    kind: 'resistance',
    tags: ['lower-compound', 'legs'],
    isCustom: false,
  },
  {
    id: 'seed-lc-safety-bar-squat',
    name: 'Safety bar squat',
    kind: 'resistance',
    tags: ['lower-compound', 'legs'],
    isCustom: false,
  },
  {
    id: 'seed-lc-box-squat',
    name: 'Box squat',
    kind: 'resistance',
    tags: ['lower-compound', 'legs'],
    isCustom: false,
  },
  {
    id: 'seed-lc-zercher-squat',
    name: 'Zercher squat',
    kind: 'resistance',
    tags: ['lower-compound', 'legs'],
    isCustom: false,
  },
  {
    id: 'seed-lc-hack-squat',
    name: 'Hack squat (machine)',
    kind: 'resistance',
    tags: ['lower-compound', 'legs', 'machine'],
    isCustom: false,
  },
  {
    id: 'seed-lc-leg-press',
    name: 'Leg press',
    kind: 'resistance',
    tags: ['lower-compound', 'legs', 'machine'],
    isCustom: false,
  },

  // 🟡 Unilateral / multi-planar
  {
    id: 'seed-uni-bulgarian-split-squat',
    name: 'Bulgarian split squat',
    kind: 'resistance',
    tags: ['unilateral', 'legs'],
    isCustom: false,
  },
  {
    id: 'seed-uni-step-downs-forward',
    name: 'Step-downs (forward)',
    kind: 'resistance',
    tags: ['unilateral', 'legs'],
    isCustom: false,
  },
  {
    id: 'seed-uni-lateral-step-downs',
    name: 'Lateral step-downs',
    kind: 'resistance',
    tags: ['unilateral', 'legs'],
    isCustom: false,
  },
  {
    id: 'seed-uni-reverse-lunges',
    name: 'Reverse lunges',
    kind: 'resistance',
    tags: ['unilateral', 'legs'],
    isCustom: false,
  },
  {
    id: 'seed-uni-walking-lunges',
    name: 'Walking lunges',
    kind: 'resistance',
    tags: ['unilateral', 'legs'],
    isCustom: false,
  },
  {
    id: 'seed-uni-lateral-lunges',
    name: 'Lateral lunges',
    kind: 'resistance',
    tags: ['unilateral', 'legs'],
    isCustom: false,
  },
  {
    id: 'seed-uni-cossack-squats',
    name: 'Cossack squats',
    kind: 'resistance',
    tags: ['unilateral', 'legs'],
    isCustom: false,
  },
  {
    id: 'seed-uni-single-leg-rdl',
    name: 'Single-leg RDL',
    kind: 'resistance',
    tags: ['unilateral', 'hamstrings', 'legs'],
    isCustom: false,
  },
  {
    id: 'seed-uni-skater-squats',
    name: 'Skater squats',
    kind: 'resistance',
    tags: ['unilateral', 'legs'],
    isCustom: false,
  },
  {
    id: 'seed-uni-landmine-curtsy',
    name: 'Landmine Zercher curtsy squat',
    kind: 'resistance',
    tags: ['unilateral', 'legs'],
    isCustom: false,
  },

  // 🟢 Hamstrings
  {
    id: 'seed-ham-rdl',
    name: 'Romanian deadlift (RDL)',
    kind: 'resistance',
    tags: ['hamstrings', 'legs', 'posterior'],
    isCustom: false,
  },
  {
    id: 'seed-ham-nordic-curls',
    name: 'Nordic curls',
    kind: 'resistance',
    tags: ['hamstrings', 'posterior'],
    isCustom: false,
  },
  {
    id: 'seed-ham-machine-curl',
    name: 'Hamstring curl (machine)',
    kind: 'resistance',
    tags: ['hamstrings', 'posterior', 'machine'],
    isCustom: false,
  },
  {
    id: 'seed-ham-swiss-ball-curl',
    name: 'Swiss ball leg curls',
    kind: 'resistance',
    tags: ['hamstrings', 'posterior'],
    isCustom: false,
  },
  {
    id: 'seed-ham-hip-hinge-banded',
    name: 'Hip hinge (banded)',
    kind: 'resistance',
    tags: ['hamstrings', 'posterior'],
    isCustom: false,
  },
  {
    id: 'seed-ham-good-mornings',
    name: 'Good mornings',
    kind: 'resistance',
    tags: ['hamstrings', 'posterior'],
    isCustom: false,
  },
  {
    id: 'seed-ham-glute-ham-raise',
    name: 'Glute-ham raise',
    kind: 'resistance',
    tags: ['hamstrings', 'posterior'],
    isCustom: false,
  },
  {
    id: 'seed-ham-slider-curls',
    name: 'Slider leg curls',
    kind: 'resistance',
    tags: ['hamstrings', 'posterior'],
    isCustom: false,
  },
  {
    id: 'seed-ham-kettlebell-swings',
    name: 'Kettlebell swings',
    kind: 'resistance',
    tags: ['hamstrings', 'posterior', 'power'],
    isCustom: false,
  },

  // 🔵 Glutes
  {
    id: 'seed-glu-hip-thrust',
    name: 'Hip thrust',
    kind: 'resistance',
    tags: ['glutes', 'legs'],
    isCustom: false,
  },
  {
    id: 'seed-glu-sl-hip-thrust',
    name: 'Single-leg hip thrust',
    kind: 'resistance',
    tags: ['glutes', 'unilateral', 'legs'],
    isCustom: false,
  },
  {
    id: 'seed-glu-glute-bridge',
    name: 'Glute bridge',
    kind: 'resistance',
    tags: ['glutes', 'legs'],
    isCustom: false,
  },
  {
    id: 'seed-glu-cable-kickbacks',
    name: 'Cable kickbacks',
    kind: 'resistance',
    tags: ['glutes', 'legs'],
    isCustom: false,
  },
  {
    id: 'seed-glu-step-ups',
    name: 'Step-ups',
    kind: 'resistance',
    tags: ['glutes', 'legs', 'unilateral'],
    isCustom: false,
  },
  {
    id: 'seed-glu-reverse-hypers',
    name: 'Reverse hypers',
    kind: 'resistance',
    tags: ['glutes', 'posterior'],
    isCustom: false,
  },
  {
    id: 'seed-glu-frog-pumps',
    name: 'Frog pumps',
    kind: 'resistance',
    tags: ['glutes', 'legs'],
    isCustom: false,
  },
  {
    id: 'seed-glu-banded-lateral-walks',
    name: 'Banded lateral walks',
    kind: 'resistance',
    tags: ['glutes', 'legs'],
    isCustom: false,
  },
  {
    id: 'seed-glu-hip-airplane',
    name: 'Hip airplane (advanced control)',
    kind: 'resistance',
    tags: ['glutes', 'unilateral'],
    isCustom: false,
  },
  {
    id: 'seed-glu-elevated-split-squat',
    name: 'Elevated split squat (glute bias)',
    kind: 'resistance',
    tags: ['glutes', 'unilateral', 'legs'],
    isCustom: false,
  },

  // 🟣 Calves & lower leg
  {
    id: 'seed-calves-standing-raises',
    name: 'Standing calf raises',
    kind: 'resistance',
    tags: ['calves', 'lower-leg'],
    isCustom: false,
  },
  {
    id: 'seed-calves-seated-raises',
    name: 'Seated calf raises',
    kind: 'resistance',
    tags: ['calves', 'lower-leg', 'soleus'],
    isCustom: false,
  },
  {
    id: 'seed-calves-sl-raises',
    name: 'Single-leg calf raises',
    kind: 'resistance',
    tags: ['calves', 'lower-leg', 'unilateral'],
    isCustom: false,
  },
  {
    id: 'seed-calves-bent-knee-raises',
    name: 'Bent-knee calf raises (soleus)',
    kind: 'resistance',
    tags: ['calves', 'lower-leg', 'soleus'],
    isCustom: false,
  },
  {
    id: 'seed-calves-tibialis-raises',
    name: 'Tibialis raises',
    kind: 'resistance',
    tags: ['calves', 'lower-leg', 'tibialis'],
    isCustom: false,
  },
  {
    id: 'seed-calves-heel-walks',
    name: 'Heel walks',
    kind: 'resistance',
    tags: ['calves', 'lower-leg'],
    isCustom: false,
  },
  {
    id: 'seed-calves-toe-walks',
    name: 'Toe walks',
    kind: 'resistance',
    tags: ['calves', 'lower-leg'],
    isCustom: false,
  },
  {
    id: 'seed-calves-jump-rope',
    name: 'Jump rope',
    kind: 'resistance',
    tags: ['calves', 'lower-leg', 'cardio'],
    isCustom: false,
  },
  {
    id: 'seed-calves-iso-holds',
    name: 'Isometric calf holds',
    kind: 'resistance',
    tags: ['calves', 'lower-leg'],
    isCustom: false,
  },
  {
    id: 'seed-calves-eccentric-lowers',
    name: 'Eccentric calf lowers',
    kind: 'resistance',
    tags: ['calves', 'lower-leg'],
    isCustom: false,
  },

  // ⚫ Core
  {
    id: 'seed-core-dead-bugs',
    name: 'Dead bugs',
    kind: 'resistance',
    tags: ['core', 'anti-extension'],
    isCustom: false,
  },
  {
    id: 'seed-core-ab-wheel',
    name: 'Ab wheel rollouts',
    kind: 'resistance',
    tags: ['core', 'anti-extension'],
    isCustom: false,
  },
  {
    id: 'seed-core-plank-variations',
    name: 'Plank variations',
    kind: 'resistance',
    tags: ['core', 'anti-extension'],
    isCustom: false,
  },
  {
    id: 'seed-core-pallof-press',
    name: 'Pallof press',
    kind: 'resistance',
    tags: ['core', 'anti-rotation'],
    isCustom: false,
  },
  {
    id: 'seed-core-cable-chops',
    name: 'Cable chops',
    kind: 'resistance',
    tags: ['core', 'anti-rotation'],
    isCustom: false,
  },
  {
    id: 'seed-core-landmine-rotations',
    name: 'Landmine rotations',
    kind: 'resistance',
    tags: ['core', 'rotation'],
    isCustom: false,
  },
  {
    id: 'seed-core-side-plank',
    name: 'Side plank',
    kind: 'resistance',
    tags: ['core', 'frontal-plane'],
    isCustom: false,
  },
  {
    id: 'seed-core-copenhagen-plank',
    name: 'Copenhagen plank',
    kind: 'resistance',
    tags: ['core', 'frontal-plane'],
    isCustom: false,
  },
  {
    id: 'seed-core-hanging-leg-raises',
    name: 'Hanging leg raises',
    kind: 'resistance',
    tags: ['core', 'dynamic'],
    isCustom: false,
  },
  {
    id: 'seed-core-farmer-carries',
    name: 'Farmer carries',
    kind: 'resistance',
    tags: ['core', 'carry', 'dynamic'],
    isCustom: false,
  },

  // ⚪ Upper push (additional)
  {
    id: 'seed-push-db-bench',
    name: 'DB bench press',
    kind: 'resistance',
    tags: ['upper-push', 'chest', 'push'],
    isCustom: false,
  },
  {
    id: 'seed-push-incline-db',
    name: 'Incline DB press',
    kind: 'resistance',
    tags: ['upper-push', 'chest', 'push'],
    isCustom: false,
  },
  {
    id: 'seed-push-landmine-press',
    name: 'Landmine press',
    kind: 'resistance',
    tags: ['upper-push', 'push', 'shoulders'],
    isCustom: false,
  },
  {
    id: 'seed-push-push-ups',
    name: 'Push-ups',
    kind: 'resistance',
    tags: ['upper-push', 'chest', 'push'],
    isCustom: false,
  },
  {
    id: 'seed-push-dips',
    name: 'Dips',
    kind: 'resistance',
    tags: ['upper-push', 'chest', 'push'],
    isCustom: false,
  },
  {
    id: 'seed-push-arnold-press',
    name: 'Arnold press',
    kind: 'resistance',
    tags: ['upper-push', 'push', 'shoulders'],
    isCustom: false,
  },
  {
    id: 'seed-push-machine-chest',
    name: 'Machine chest press',
    kind: 'resistance',
    tags: ['upper-push', 'chest', 'machine'],
    isCustom: false,
  },
  {
    id: 'seed-push-cable-press',
    name: 'Cable press',
    kind: 'resistance',
    tags: ['upper-push', 'chest', 'push'],
    isCustom: false,
  },

  // ⚪ Upper pull (additional)
  {
    id: 'seed-pull-chin-ups',
    name: 'Chin-ups',
    kind: 'resistance',
    tags: ['upper-pull', 'pull', 'back'],
    isCustom: false,
  },
  {
    id: 'seed-pull-muscle-ups',
    name: 'Muscle-ups',
    kind: 'resistance',
    tags: ['upper-pull', 'pull', 'back'],
    isCustom: false,
  },
  {
    id: 'seed-pull-lat-pulldown',
    name: 'Lat pulldown',
    kind: 'resistance',
    tags: ['upper-pull', 'pull', 'back', 'machine'],
    isCustom: false,
  },
  {
    id: 'seed-pull-db-rows',
    name: 'DB rows',
    kind: 'resistance',
    tags: ['upper-pull', 'pull', 'back'],
    isCustom: false,
  },
  {
    id: 'seed-pull-seated-cable-rows',
    name: 'Seated cable rows',
    kind: 'resistance',
    tags: ['upper-pull', 'pull', 'back'],
    isCustom: false,
  },
  {
    id: 'seed-pull-face-pulls',
    name: 'Face pulls',
    kind: 'resistance',
    tags: ['upper-pull', 'pull', 'rear-delts'],
    isCustom: false,
  },
  {
    id: 'seed-pull-inverted-rows',
    name: 'Inverted rows',
    kind: 'resistance',
    tags: ['upper-pull', 'pull', 'back'],
    isCustom: false,
  },
  {
    id: 'seed-pull-straight-arm-pulldowns',
    name: 'Straight-arm pulldowns',
    kind: 'resistance',
    tags: ['upper-pull', 'pull', 'back'],
    isCustom: false,
  },

  // Activities (unchanged)
  {
    id: 'seed-climb',
    name: 'Climbing',
    kind: 'activity',
    tags: ['sport'],
    isCustom: false,
  },
  {
    id: 'seed-boulder',
    name: 'Bouldering',
    kind: 'activity',
    tags: ['sport'],
    isCustom: false,
  },
  {
    id: 'seed-run',
    name: 'Running',
    kind: 'activity',
    tags: ['cardio'],
    isCustom: false,
  },
  {
    id: 'seed-swim',
    name: 'Swimming',
    kind: 'activity',
    tags: ['cardio'],
    isCustom: false,
  },
  {
    id: 'seed-cycle',
    name: 'Cycling',
    kind: 'activity',
    tags: ['cardio'],
    isCustom: false,
  },
  {
    id: 'seed-meditate',
    name: 'Meditation',
    kind: 'activity',
    tags: ['mindfulness', 'recovery'],
    isCustom: false,
  },
]

SEED_EXERCISES.forEach((e) => SEED_IDS.add(e.id))

export function isSeedExerciseId(id: string): boolean {
  return SEED_IDS.has(id)
}

export async function ensureSeedExercises(): Promise<void> {
  await db.transaction('rw', db.exercises, async () => {
    for (const ex of SEED_EXERCISES) {
      await db.exercises.put(ex)
    }
  })
}
